### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by andy-maier** [click-contrib/click-repl#73]
Sorry for asking so directly, but the last release was in 10/2018, and since then none of the PRs that had been provided have been answered to or merged.

**Comment by untitaker** [comment]
Hey, I'm no longer using this project. I think I would be happy to hand this over to any person who seems to have a trustworthy track record in OSS (not any volunteer since this package is depended upon by quite a few people)

**Comment by auvipy** [comment]
> Hey, I'm no longer using this project. I think I would be happy to hand this over to any person who seems to have a trustworthy track record in OSS (not any volunteer since this package is depended upon by quite a few people)

Hi, I am a celery core team member, we use this in celery if you add me to maintain this project I can keep it updated & released for the sake of compatibility with celery & airflow.

**Comment by untitaker** [comment]
@auvipy added

ping me for release though, I will add you later to PyPI but I wanna take a quick look at things you merged before the next big release after such a long time.

**Comment by auvipy** [comment]
ok sure

**Comment by davidism** [comment]
@auvipy heads up, if you are a maintainer now, this will stop working when Click 8 is released because the shell completion system was rewritten.

Celery currently depends on Click < 8, but Flask 2 will depend on Click >= 8, so anyone using Flask with Celery will not be able to upgrade until Celery updates their pin, which they can't unless they drop this dependency or it gets updated.

**Comment by auvipy** [comment]
Yup some big overhaull needed

**Comment by auvipy** [comment]
I need some details on click changes that need to be worked on to make it v8.0 compatible

**Comment by davidism** [comment]
@auvipy I'm not familiar with click-repl, so I'm not exactly sure what might be needed. However, the only thing that significantly changed in an incompatible way was the shell completion system. Commands, groups, parameters, and types all have `shell_complete` methods now instead of having to go through internals. The completion system itself is extensible and a public API, it has moved to the `click.shell_completion` module. https://click.palletsprojects.com/en/master/shell-completion/#custom-type-completion Happy to answer more questions on the Click channel on our Discord: https://discord.gg/pallets

**Comment by andy-maier** [comment]
@auvipy Hey, this is great. Thanks!

**Comment by auvipy** [comment]
we have a new release. @untitaker it would be a very helpful if i get acess to other packages like click-didyoumean &
click-plugins as we use them in celery :) ofcourse if you have the ability to invite on those repo as well.

**Comment by auvipy** [comment]
I am closing this since the project is alive now with new release.

**Comment by untitaker** [comment]
@auvipy those packages have their own maintainers respectively, if you want to have access on them please create a new issue there respectively. I can take care of the details if the respective maintainer agrees.

**Comment by auvipy** [comment]
ok
